# hostname (and path) to the root eg. https://appernetic.github.io/
baseurl = "http://3dquu.com/"

DefaultContentLanguage = "en"

# If you want all of the languages to be put below their respective language code,
# enable DefaultContentLanguageInSubdir = true. Without enabling it english content
# will be in the root and other languages in their respective subfolder such as /sv/.
# See [Languages] settings at the end of this file.

# Language
languageCode = "en"

# SES friendly url:s
canonifyurls = true

# Frontmatter format
# "yaml", "toml", "json"
metaDataFormat = "toml"

# Theme to use (located in /themes/THEMENAME/)
theme = "hugo-bootstrap-premium"
# Pagination
paginate = 10
paginatePath = "page"

# Enable Disqus integration
disqusShortname = "3dquu"


[permalinks]
post = "/:year/:month/:day/:slug/"
code = "/:slug/"

[taxonomies]
tag = "tags"
topic = "topics"

[author]
name = "Ulfsv"
email = "ulf.e.sv@gmail.com"

#
# All parameters below here are optional and can be mixed and matched.
#

[params.theme]
name = "paper"

[params.popover]
# This is a highly configurable popover form.
enablepopover = false #enable or disable popover: true/false.
posturl = "https://zapier.com/hooks/catch/1227563/" # Your zapier post hook.
headerimage = "//placehold.it/1000x600"
expirecookie = 5 #show it again after number of days to visitors that has not subscribed.
cookiename = "mycookie1" #give the cookie a unique name variable (avoid spaces and strange characters).
signupheader = "Join Our Newsletter"
showmodaltimeout = 10000 #show popover modal after time interval in milliseconds.
mouseleave = true #show popover when mouse leaves window: true/false.
modalsize = "" #lg or sm. Empty is md. If phone is detected lg is used.
imagedescription = "Placeholder image for this popover modal optin form"
signuptext = "Signup today for free and be the first to get notified on new updates."
inputplaceholder = "Enter your email"
submitbutton = "Subscribe"
successmessage = "Thanks for your subscription!"
errormessage = "Submitting form failed!"
optin = true #opt-in: true/false

[params]
# You can use markdown here.
BrandImage = "https://res.cloudinary.com/dtnahfj7l/v1489354290/ldn7ds6wbbx6rtvjqx55" #top header brand image.
brand = "3DQuu" # brand image alt text.
topline = "3DQuu"
footline = "code with <i class='fa fa-heart'></i>"

# Text for the top menu link, which goes to the root URL for the site.
# Default (if omitted) is "Home".
home = "Home"

mailmunchid = "" # Mailmunch site id
sumomeid = "" # Sumome id

# Show a sidebar menu
showRightSidebar = false
# Select a syntax highlight.
# Check the static/css/highlight directory for options.
highlight = "default"

# Google Analytics.
googleAnalytics = "UA-96210901-1"

# Sidebar social links.
github = "" # Your Github profile ID
bitbucket = "" # Your Bitbucket profile ID
linkedin = "" # Your LinkedIn profile ID (from public URL)
googleplus = "" # Your Google+ profile ID
facebook = "" # Your Facebook profile ID
twitter = "" # Your Twitter profile ID
youtube = ""  # Your Youtube channel ID
flattr = ""  # populate with your flattr uid

[blackfriday]
angledQuotes = true
fractions = false
hrefTargetBlank = false
latexDashes = true
plainIdAnchors = true
extensions = []
extensionmask = []

# Menus
# If you want active menu items highlighted for internal pages don't add them here, they need to be added in each files front matter.
# like this:
#[menu]
#     [menu.main]
#        name = "Showcase"
#        weight = 3
#        identifier = "showcase"

[Languages]
[Languages.en]
weight = 1
copyright = "(c) 2017 Copyright 3DQuu"
title = "3DQuu" # Site title

[[Languages.en.menu.main]]
name = "Blog"
pre = ""
weight = 2
identifier = "post"
url = "/post/"


#[Languages.sv]
#weight = 2
#title = "Min blog" # Site title
#copyright = "(c) 2017 Alla rättigheter 3DQuu"

#[[Languages.sv.menu.main]]
#name = "Bloggen"
#pre = ""
#weight = 2
#identifier = "post"
#url = "/sv/post/"



[Languages.sv.taxonomies]
tag = "Taggar"
topic = "Ämne"
